env:
  results_dir: './results/ibn50/'
  use_gpu: False
  data_parallel: True
  sync_bn: False

lightreid:
  light_model: False
  light_feat: False
  light_search: False

data:
  sources: [ 'dukemtmcreid', 'market1501', 'msmt17', 'wildtrack_crop', 'rap', 'njust365win', 'cuhk03' ]
  targets: [ 'dukemtmcreid', 'market1501', 'msmt17', 'njust365win', 'cuhk03' ]
  img_size: [256, 128] # height, width
  transforms_train: ['randomflip', 'padcrop', 'rea']
  transforms_test: []
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  sampler: 'pk'
  p: 6
  k: 24

model:
  backbone:
    name: 'resnet50ibna'
    last_stride_one: True
    pretrained: True
    map_location: 'cpu'
  pooling:
    name: 'avgpool'
  head:
    name: 'bnhead'
    classifier:
      name: 'circle'
      scale: 64
      margin: 0.35

criterion:
  loss1:
    display_name: 'classification_loss'
    criterion:
      name: 'cross_entropy_label_smooth'
    inputs:
      inputs: 'logits'
      targets: 'pids'
    weight: 1.0
  loss2:
    display_name: 'triplet_loss'
    criterion:
      name: 'tripletloss'
      margin: 0.35
      metric: 'euclidean'
    inputs:
      emb: 'feats'
      label: 'pids'
    weight: 1.0

optim:
  optimizer:
    name: 'adam'
    lr: 3.5e-4
    weight_decay: 5.0e-4
  lr_scheduler:
    name: 'warmup_multistep'
    milestones: [20, 45]
    gamma: 0.1
    warmup_factor: 0.01
    warmup_epochs: 5
  max_epochs: 60

